# Generated by Django 4.2.26 on 2025-12-06 14:38

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import scripts.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('institute', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Orderer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('orderer', models.CharField(max_length=255)),
                ('no', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('code', models.IntegerField()),
                ('purpose', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('code', 'purpose')},
            },
        ),
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('size', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScriptStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purpose_ScriptStatus', to='scripts.purpose')),
                ('scripts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts_ScriptStatus', to='scripts.scripts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScriptSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('scripts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts_ScriptSize', to='scripts.scripts')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_ScriptSize', to='scripts.size')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScriptsIsbn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('isbn', models.CharField(max_length=20)),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purpose_ScriptsIsbn', to='scripts.purpose')),
                ('scripts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts_ScriptsIsbn', to='scripts.scripts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScriptOrderer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('orderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderer_ScriptOrderer', to='scripts.orderer')),
                ('scripts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts_ScriptOrderer', to='scripts.scripts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScriptInstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_ScriptInstitute', to='scripts.institute')),
                ('scripts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts_ScriptInstitute', to='scripts.scripts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScriptDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('scripts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts_ScriptDescription', to='scripts.scripts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionEbookStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purpose_ProductionEbookStatus', to='scripts.purpose')),
                ('scripts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts_ProductionEbookStatus', to='scripts.scripts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoverStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purpose_CoverStatus', to='scripts.purpose')),
                ('scripts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts_CoverStatus', to='scripts.scripts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('object_id', models.CharField(max_length=255)),
                ('action', models.IntegerField()),
                ('changes', models.JSONField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
