# Generated by Django 5.2.8 on 2026-01-07 03:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import scripts.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Institute',
                'verbose_name_plural': 'Institutes',
                'db_table': 'institute',
            },
        ),
        migrations.CreateModel(
            name='LabelStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'LabelStatus',
                'verbose_name_plural': 'LabelStatuss',
                'db_table': 'labelstatus',
            },
        ),
        migrations.CreateModel(
            name='Made',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Made',
                'verbose_name_plural': 'Mades',
                'db_table': 'made',
            },
        ),
        migrations.CreateModel(
            name='No',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('no', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SectionDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'SectionDescription',
                'verbose_name_plural': 'SectionDescriptions',
                'db_table': 'sectiondescription',
            },
        ),
        migrations.CreateModel(
            name='SectionFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'SectionFlaf',
                'verbose_name_plural': 'SectionFlags',
                'db_table': 'sectionflag',
            },
        ),
        migrations.CreateModel(
            name='SectionMade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'SectionMade',
                'verbose_name_plural': 'SectionMades',
                'db_table': 'sectionmade',
            },
        ),
        migrations.CreateModel(
            name='SectionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'SectionNote',
                'verbose_name_plural': 'SectionNotes',
                'db_table': 'sectionnote',
            },
        ),
        migrations.CreateModel(
            name='SectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'SectionStatus',
                'verbose_name_plural': 'SectionStatuss',
                'db_table': 'sectionstatus',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
                'db_table': 'size',
            },
        ),
        migrations.CreateModel(
            name='TypeIsbn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'TypeIsbn',
                'verbose_name_plural': 'TypeIsbns',
                'db_table': 'typeisbn',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('object_id', models.CharField(max_length=255)),
                ('action', models.IntegerField()),
                ('changes', models.JSONField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ActivityLog',
                'verbose_name_plural': 'ActivityLogs',
                'db_table': 'activitylog',
            },
        ),
        migrations.CreateModel(
            name='ByMade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_By', to=settings.AUTH_USER_MODEL)),
                ('made', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scriptsprocess_By', to='scripts.made')),
            ],
            options={
                'verbose_name': 'ByMade',
                'verbose_name_plural': 'ByMades',
                'db_table': 'bymade',
            },
        ),
        migrations.CreateModel(
            name='Orderer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('no', models.IntegerField(blank=True, null=True)),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_Orderer', to='scripts.institute')),
            ],
            options={
                'verbose_name': 'Orderer',
                'verbose_name_plural': 'Orderers',
                'db_table': 'orderer',
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_Scripts', to='scripts.institute')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_Scripts', to='scripts.size')),
            ],
        ),
        migrations.CreateModel(
            name='NoScripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_NoScripts', to='scripts.no')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts_NoScripts', to='scripts.script')),
            ],
            options={
                'verbose_name': 'NoScripts',
                'verbose_name_plural': 'NoScriptss',
                'db_table': 'noscripts',
            },
        ),
        migrations.AddField(
            model_name='no',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts_No', to='scripts.script'),
        ),
        migrations.AddField(
            model_name='made',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts_ScriptsProcess', to='scripts.script'),
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('thumbnail', models.CharField(max_length=255)),
                ('length', models.IntegerField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('x_axis', models.IntegerField(default=0)),
                ('y_axis', models.IntegerField(default=0)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts_Cover', to='scripts.script')),
            ],
            options={
                'verbose_name': 'Cover',
                'verbose_name_plural': 'Covers',
                'db_table': 'cover',
            },
        ),
        migrations.CreateModel(
            name='ScriptsOrderer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('orderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderer_ScriptsOrderer', to='scripts.orderer')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts_ScriptsOrderer', to='scripts.script')),
            ],
            options={
                'verbose_name': 'ScriptsOrderer',
                'verbose_name_plural': 'ScriptsOrderers',
                'db_table': 'scriptsorderer',
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts_Description', to='scripts.script')),
                ('sectiondescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptionpart_Description', to='scripts.sectiondescription')),
            ],
            options={
                'verbose_name': 'Description',
                'verbose_name_plural': 'Descriptions',
                'db_table': 'description',
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('scripts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts_Flag', to='scripts.script')),
                ('sectionflag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_Flag', to='scripts.sectionflag')),
            ],
            options={
                'verbose_name': 'Flag',
                'verbose_name_plural': 'Flags',
                'db_table': 'flag',
            },
        ),
        migrations.AddField(
            model_name='made',
            name='sectionmade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_ScriptsProcess', to='scripts.sectionmade'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts_Note', to='scripts.script')),
                ('sectionnote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notepart_Note', to='scripts.sectionnote')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'note',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('labelstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_Status', to='scripts.labelstatus')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts_Status', to='scripts.script')),
                ('sectionstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_Status', to='scripts.sectionstatus')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuss',
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='TextDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('text', models.CharField(max_length=255)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_Text', to='scripts.description')),
            ],
            options={
                'verbose_name': 'TextDescription',
                'verbose_name_plural': 'TextDescriptions',
                'db_table': 'textdescription',
            },
        ),
        migrations.CreateModel(
            name='TextNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('text', models.CharField(max_length=255)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_Content', to='scripts.note')),
            ],
            options={
                'verbose_name': 'TextNote',
                'verbose_name_plural': 'TextNotes',
                'db_table': 'textnote',
            },
        ),
        migrations.CreateModel(
            name='Isbn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('isbn', models.CharField(max_length=20)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts_ISBN', to='scripts.script')),
                ('typeisbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_ISBN', to='scripts.typeisbn')),
            ],
            options={
                'verbose_name': 'Isbn',
                'verbose_name_plural': 'Isbns',
                'db_table': 'isbn',
            },
        ),
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
