# Generated by Django 4.2.26 on 2025-12-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purpose',
            name='code',
            field=models.IntegerField(db_index=True),
        ),
    ]
