# Generated by Django 5.2.8 on 2025-12-24 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='textdescription',
            new_name='sectiondescription',
        ),
    ]
