# Generated by Django 5.2.8 on 2025-12-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
