# Generated by Django 5.2.8 on 2025-12-09 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covercolor',
            old_name='covercolor',
            new_name='color',
        ),
    ]
