# Generated by Django 4.2.26 on 2025-12-28 05:14

from django.db import migrations, models
import django.db.models.deletion
import scripts.utils


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionOrderer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='scriptsorderer',
            name='sectionorderer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectionorderer_ScriptsOrderer', to='scripts.sectionorderer'),
        ),
    ]
