# Generated by Django 5.2.8 on 2025-12-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bymade',
            options={'verbose_name': 'ByMade', 'verbose_name_plural': 'ByMades'},
        ),
        migrations.AlterModelOptions(
            name='made',
            options={'verbose_name': 'Made', 'verbose_name_plural': 'Mades'},
        ),
        migrations.AlterModelOptions(
            name='sectionflag',
            options={'verbose_name': 'SectionFlaf', 'verbose_name_plural': 'SectionFlags'},
        ),
        migrations.AlterModelOptions(
            name='sectionmade',
            options={'verbose_name': 'SectionMade', 'verbose_name_plural': 'SectionMades'},
        ),
        migrations.AlterModelTable(
            name='bymade',
            table='bymade',
        ),
        migrations.AlterModelTable(
            name='made',
            table='made',
        ),
        migrations.AlterModelTable(
            name='sectionflag',
            table='sectionflag',
        ),
        migrations.AlterModelTable(
            name='sectionmade',
            table='sectionmade',
        ),
    ]
