# Generated by Django 4.2.26 on 2025-12-18 14:47

from django.db import migrations, models
import django.db.models.deletion
import scripts.utils


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('thumbnail', models.CharField(max_length=255)),
                ('length', models.IntegerField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('x_axis', models.IntegerField(default=0)),
                ('y_axis', models.IntegerField(default=0)),
                ('scripts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts_Cover', to='scripts.scripts')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
