# Generated by Django 4.2.26 on 2025-12-28 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='TypeIsbn',
        ),
        migrations.RenameField(
            model_name='isbn',
            old_name='type',
            new_name='typeisbn',
        ),
    ]
