# Generated by Django 4.2.26 on 2025-12-28 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_rename_type_typeisbn_rename_type_isbn_typeisbn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Part',
            new_name='SectionFlag',
        ),
        migrations.AlterModelOptions(
            name='typeisbn',
            options={'ordering': ['name'], 'verbose_name': 'TypeIsbn', 'verbose_name_plural': 'TypeIsbns'},
        ),
        migrations.RenameField(
            model_name='flag',
            old_name='part',
            new_name='sectionflag',
        ),
        migrations.AlterModelTable(
            name='typeisbn',
            table='typeisbn',
        ),
    ]
