# Generated by Django 5.2.8 on 2025-12-24 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_rename_textdescription_description_sectiondescription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scripts',
            new_name='Script',
        ),
        migrations.RenameField(
            model_name='no',
            old_name='scripts',
            new_name='script',
        ),
        migrations.RenameField(
            model_name='noscripts',
            old_name='scripts',
            new_name='script',
        ),
    ]
