# Generated by Django 4.2.26 on 2025-12-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_sectionorderer_scriptsorderer_sectionorderer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scriptsorderer',
            name='sectionorderer',
        ),
        migrations.DeleteModel(
            name='SectionOrderer',
        ),
    ]
