# Generated by Django 4.2.26 on 2025-12-06 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import scripts.utils


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_alter_purpose_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScriptDescription',
            new_name='ScriptsDescription',
        ),
        migrations.AddField(
            model_name='coverstatus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CoverStatusDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=scripts.utils.current_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('coverstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverstatus_CoverStatusDescription', to='scripts.coverstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
