# Generated by Django 4.2.26 on 2025-12-07 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_rename_scriptdescription_scriptsdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderer',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_Orderer', to='scripts.institute'),
        ),
    ]
